language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 5.6
          env: SYMFONY_VERSION='2.8.*' SYMFONY_DEPRECATIONS_HELPER=weak
          # Remove SYMFONY_DEPRECATIONS_HELPER when https://github.com/symfony/assetic-bundle/pull/395 is released.
        - php: 5.6
          env: SYMFONY_VERSION='3.0.*'
    fast_finish: true

install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - composer update --no-interaction --prefer-source $COMPOSER_FLAGS

script:
    - phpunit --coverage-text --colors
    - php ./vendor/bin/phpcs --standard=psr2 Admin/ Broadcaster/ Command/ DependencyInjection/ Entity/ Event/ EventListener/ Exception/ Resources/ Service/ Tests/ LiveBroadcastBundle.php
